// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl2n3Ys3GboUfEjEO38DVB4nmN7YYolp4',
    appId: '1:145968609390:web:28ca47d84e1ec116f90e7f',
    messagingSenderId: '145968609390',
    projectId: 'responsi2-inventaris-buku',
    authDomain: 'responsi2-inventaris-buku.firebaseapp.com',
    storageBucket: 'responsi2-inventaris-buku.firebasestorage.app',
    measurementId: 'G-32ZP4X1DWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBss2JOMoyhr0Zzoct5ErXuze6-bXOMlJc',
    appId: '1:145968609390:android:f42cd86b7488b801f90e7f',
    messagingSenderId: '145968609390',
    projectId: 'responsi2-inventaris-buku',
    storageBucket: 'responsi2-inventaris-buku.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl2n3Ys3GboUfEjEO38DVB4nmN7YYolp4',
    appId: '1:145968609390:web:af1d8bcee9fc139cf90e7f',
    messagingSenderId: '145968609390',
    projectId: 'responsi2-inventaris-buku',
    authDomain: 'responsi2-inventaris-buku.firebaseapp.com',
    storageBucket: 'responsi2-inventaris-buku.firebasestorage.app',
    measurementId: 'G-EPSBDKHVXK',
  );
}
